apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-service
  namespace: log-output
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
